language: php
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - phpunit --coverage-text --coverage-clover=coverage.clover